car:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  # Velocity controllers
  left_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: left_motor_wheel
    pid: {p: 0.1, i: 0.0, d: 0.0}

  right_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: right_motor_wheel
    pid: {p: 0.1, i: 0.0, d: 0.0}